/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    _Boilerplate: typeof import('./src/components/_Boilerplate.vue')['default']
    BreadCrumb: typeof import('./src/components/BreadCrumb.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    copy: typeof import('./src/components/LoadingSpinner copy.vue')['default']
    Crud: typeof import('./src/components/Crud.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    DeleteDialog: typeof import('./src/components/DeleteDialog.vue')['default']
    DeleteModal: typeof import('./src/components/DeleteModal.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    'LoadingSpinner copy': typeof import('./src/components/LoadingSpinner copy.vue')['default']
    Login: typeof import('./src/pages/authLayout/LogIn.vue')['default']
    LogIn: typeof import('./src/pages/authLayout/LogIn.vue')['default']
    Register: typeof import('./src/pages/authLayout/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
