/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/clients': RouteRecordInfo<'/admin/clients', '/admin/clients', Record<never, never>, Record<never, never>>,
    '/authLayout/AuthLayout': RouteRecordInfo<'/authLayout/AuthLayout', '/authLayout/AuthLayout', Record<never, never>, Record<never, never>>,
    '/authLayout/dashboards/AdminDashboard': RouteRecordInfo<'/authLayout/dashboards/AdminDashboard', '/authLayout/dashboards/AdminDashboard', Record<never, never>, Record<never, never>>,
    '/authLayout/dashboards/SuperDashboard': RouteRecordInfo<'/authLayout/dashboards/SuperDashboard', '/authLayout/dashboards/SuperDashboard', Record<never, never>, Record<never, never>>,
    '/authLayout/dashboards/UserDashboard': RouteRecordInfo<'/authLayout/dashboards/UserDashboard', '/authLayout/dashboards/UserDashboard', Record<never, never>, Record<never, never>>,
    '/authLayout/ForgotPassword': RouteRecordInfo<'/authLayout/ForgotPassword', '/authLayout/ForgotPassword', Record<never, never>, Record<never, never>>,
  }
}
